spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    banner-mode: console

  logging:
    pattern:
      dateformat: hh:mm
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql:
                BasicBinder: trace